### ISSUE TITLE
[feature/profile] 사용자 프로필, 농업인 프로필 페이지 구현

### ISSUE THREAD

**Issue by sb-77** [WebAppTeamPJ/HanulDure#13]
## 🛠️ 기능 설명
> 
- 사용자가 회원가입 시 입력한 정보가 보이는 프로필 페이지 구현
- 농업인이 회원가입 시 입력한 정보가 보이는 프로필 페이지 구현
- 추가로 각 사용자와 농업인이 신청한 행사도 같이 보이도록 페이지 구현

## 📝 작업 진행 체크리스트

- [x] 필요한 기능인가
- [x] 작동 확인
- [x] 최종 구현 완료

## ✅ 테스트 결과(이미지)(선택사항)
>
![famerprofile](https://github.com/WebAppTeamPJ/HanulDure/assets/105586878/93a2f7be-3691-4093-9814-0a24b96519fb)
![userprofile](https://github.com/WebAppTeamPJ/HanulDure/assets/105586878/de96e5ad-0706-4ef3-9331-14c57c95f3a3)

**Comment by hyojunahn111** [comment]
확인했습니다.
