### ISSUE TITLE
[Hanuldure/login]시작페이지, 로그인 페이지 html태그, css, Thymeleaf 적용

### ISSUE THREAD

**Issue by GTU9** [WebAppTeamPJ/HanulDure#7]
## 🛠️ 기능 설명
프로젝트 시작페이지, 로그인 페이지 html태그, css, Thymeleaf 적용

## 📝 작업 진행 체크리스트

- [x] 필요한 기능인가
- [x] 작동 확인
- [x] 최종 구현 완료

## 📚 참고 자료(선택사항)
>

## ✅ 테스트 결과(이미지)(선택사항)
![image](https://github.com/WebAppTeamPJ/HanulDure/assets/107167326/de2abd69-45db-4e58-a77c-85bfdbe2a74c)

![image](https://github.com/WebAppTeamPJ/HanulDure/assets/107167326/0b0adcac-a6cc-43ed-886d-accd2c222bc9)

**Comment by hyojunahn111** [comment]
확인했습니다.
